# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
target 'ProgramGirl' do
    pod 'Qiniu'
    pod 'RongCloudIM/IMLib', '<= 2.8.3'
    pod 'RongCloudIM/IMKit', '<= 2.8.3'
end

